### Signup - Send OTP

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/signup
Content-Type: application/json

{
    "username": "viksass",
    "email": "nikhilsinghdfg@gmail.com",
    "password": "dhn245dfgAA@"
}



### Health Check
GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/health


### Verify OTP

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/verify-otp
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com",
    "otp": " 367045"

}



### login test 

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/Login
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com",
    "password": "dhn245dfgAA@"
}

###

### Get Profile 

GET  https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/profile 
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk3MzI3LCJleHAiOjE3ODk4MDAzMjd9.YKKjUdIFYc3RKFqUAZsuc4zhi9BVmdLO7sXS6vzGkRc


### Refresh Access Token

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/refresh-token
Cookie: refreshToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImlhdCI6MTc4OTc5NzI3NiwiZXhwIjoxNzkxMDkzMjc2fQ.QMsjZpM1G99iL_hhZt3SgjfSIaOws_MNYEDz8w-Z--8; Max-Age=1296000

 


### Logout 

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/logout 
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImlhdCI6MTc4OTc5NzI3NiwiZXhwIjoxNzkxMDkzMjc2fQ.QMsjZpM1G99iL_hhZt3SgjfSIaOws_MNYEDz8w-Z--8; Max-Age=1296000


### Update Profile

PATCH https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/update-profile
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUwZDI4ZTdkYzY4YjEwNmFlNzc4OCIsImVtYWlsIjoibmlraGlsc2luZ2gzMzQ0NTVAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkxODMzLCJleHAiOjE3ODk3OTQ4MzN9.fpYMUBCCTGooN-Psza5YSUr2sopJIc7EWClqFRmbac0

{
    "username": "vimal"
}


### Change Password

PATCH https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/change-password
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUwZDI4ZTdkYzY4YjEwNmFlNzc4OCIsImVtYWlsIjoibmlraGlsc2luZ2gzMzQ0NTVAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkxODMzLCJleHAiOjE3ODk3OTQ4MzN9.fpYMUBCCTGooN-Psza5YSUr2sopJIc7EWClqFRmbac0

{
    "oldPassword": "dhn245dfgAA@",
    "newPassword": "qazQAZ123@AS#AS"
}


### Deactivate Account

PATCH https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/deactivate-account
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUwZDI4ZTdkYzY4YjEwNmFlNzc4OCIsImVtYWlsIjoibmlraGlsc2luZ2gzMzQ0NTVAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkxODMzLCJleHAiOjE3ODk3OTQ4MzN9.fpYMUBCCTGooN-Psza5YSUr2sopJIc7EWClqFRmbac0



### Delete Account

DELETE https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/delete-account
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMGI1ZTdkYzY4YjEwNmFlNzc4YiIsImVtYWlsIjoibmlraGlsc2luZ2gzMzRAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyNTQ3LCJleHAiOjE3ODk3OTU1NDd9.kXabo2ik8ScZotoD6-mlhvz3bM7G_WsO0RThVDZ4H5A

{
    "password": "dhn245dfgAA@"
}



### Forgot Password

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/forgot-password
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com"
}


### Reset Password

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/reset-password
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com",
    "otp": "195754",
    "newPassword": "dhn245dfgA@qaz",
    "confirmPassword": "dhn245dfgA@qaz"
}



##############################################################################################################################################################################################################################################################


### create new business


POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk3MzI3LCJleHAiOjE3ODk4MDAzMjd9.YKKjUdIFYc3RKFqUAZsuc4zhi9BVmdLO7sXS6vzGkRc

{
  "businessName": "Nextpen Solutions pvt lmt",
  "ownerName": "Rahul gadlhi",
  "email": "skyline.tech@example.com",
  "phone": "9123456783",
  "gstNumber": "27ABCDE1234F1Z5",
  "address": {
    "addressLine1": "45 Park Street",
    "addressLine2": "",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "400001"
  },
  "currency": "INR",
  "signature": "https://example.com/rahul-signature.png",
  "logo": "https://example.com/skyline-logo.png",
  "invoicePrefix": "SKY",
  "invoiceStartNumber": 1001,
  "termsAndConditions": "Payment is due within 15 days."
}


### get business profile

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0



### delete business profile

DELETE  https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0


### Update Business

PATCH https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0

{
  "businessName": "Nextpen pvt lmt",
  "phone": "9123456783",
  "city": "pune"
}




##############################################################################################################################################################################################################################################################

### create new product


POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/product
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE

{
    "productName": "Laptop",
    "description": "DEll 15S Laptop",
    "category": "Electronics",
    "unit": "piece",
    "price": 6000,
    "taxRate": 12,
    "discount": 5
}



### Get All Products

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/product
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0


### Get Product By ID

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/product/6aae1373e7dc68b106ae7792
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0


### Update Product

PATCH https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/product/6aae1373e7dc68b106ae7792
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0


{
    "productName": "Dell Inspiron 15",
    "description": "Dell Inspiron 15 12th Gen Intel i5 Laptop",
    "category": "Electronics",
    "unit": "piece",
    "price": 58999,
    "taxRate": 18,
    "discount": 10
}

### Delete Product

DELETE https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/product/6aae1373e7dc68b106ae7792
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0



##############################################################################################################################################################################################################################################################


### Create Customer

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/customer
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE


{
    "customerName": "raj",
    "email": "nikhilsingh2764@gmail.com",
    "phone": "8407937952",
    "companyName": "TechNova Solutions",
    "gstNumber": "27ABCDE1234F1Z5",
    "customerType": "Business",
    "notes": "Preferred customer",

    "billingAddress": {
        "addressLine1": "101 Park Street",
        "addressLine2": "Near City Mall",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411001"
    },

    "shippingAddress": {
        "addressLine1": "Warehouse 5",
        "addressLine2": "MIDC Phase 2",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411045"
    }
}

### Get All Customers

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/customer
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk3MzI3LCJleHAiOjE3ODk4MDAzMjd9.YKKjUdIFYc3RKFqUAZsuc4zhi9BVmdLO7sXS6vzGkRc


### Get Customer By ID

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/customer/6aae1480e7dc68b106ae7796
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0






### Update Customer

PATCH https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/customer/6aae1480e7dc68b106ae7796
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0

{
    "customerName": "Priya Verma Updated",
    "phone": "9988776655",
    "companyName": "TechNova Pvt Ltd",
    "notes": "VIP customer",

    "billingAddress": {
        "addressLine1": "202 FC Road",
        "addressLine2": "Near Metro Station",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411004"
    }
}





### Delete Customer

DELETE https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/customer/6aae1480e7dc68b106ae7796
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxMWU0ZTdkYzY4YjEwNmFlNzc4ZCIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5NzkyOTc5LCJleHAiOjE3ODk3OTU5Nzl9.3Wvt-JHLhJrChL0k7mVma-rX_f_FP8BMpVO1G6O5_L0




##############################################################################################################################################################################################################################################################


### Create Invoice

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/invoice
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE

{
  "customerId": "6aae2caca8ade6dc874494e9",
  "items": [
    {
      "productId": "6aae2cc5a8ade6dc874494ea",
      "quantity": 4
    }
  ],
"dueDate": "2026-02-01",
  "status": "Pending",
  "notes": "Invoice 9"
}


### Get Invoice By ID

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/invoice/6aae247bc6c943cc8ad728a6
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk3MzI3LCJleHAiOjE3ODk4MDAzMjd9.YKKjUdIFYc3RKFqUAZsuc4zhi9BVmdLO7sXS6vzGkRc





### Update Invoice


PATCH https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/invoice/6aae247bc6c943cc8ad728a6
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk3MzI3LCJleHAiOjE3ODk4MDAzMjd9.YKKjUdIFYc3RKFqUAZsuc4zhi9BVmdLO7sXS6vzGkRc

{
  "customerId": "6aae2426c6c943cc8ad728a4",
  "items": [
    {
      "productId": "6aae241cc6c943cc8ad728a3",
      "quantity": 3
    }
  ],
  "dueDate": "2026-08-10",
  "status": "Paid",
  "notes": "Updated invoice after customer request"
}




### delete Invoice


DELETE  https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/invoice/6aae247bc6c943cc8ad728a6
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk3MzI3LCJleHAiOjE3ODk4MDAzMjd9.YKKjUdIFYc3RKFqUAZsuc4zhi9BVmdLO7sXS6vzGkRc



### Send Invoice Email

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/invoice/6aae2988a8ade6dc874494e7/email
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE





### Download Invoice PDF

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/invoice/6aae2988a8ade6dc874494e7/pdf
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE


### Duplicate Invoice

POST https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/invoice/6aae2988a8ade6dc874494e7/duplicate
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE





###################################################################################################################

### Dashboard Stats

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE

### Dashboard Search Test

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard/?search=raj
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE


### Dashboard Filter By Status - Paid

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard/?status=Paid
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE



### Dashboard Filter By Status - Pending

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard/?status=Pending
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE


### Dashboard Sort Latest Invoice First

GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard/?sort=-createdAt
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE



### Dashboard Sort Oldest Invoice First


GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard/?sort=createdAt
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE


### Dashboard Pagination Page 1 Limit 5


GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard/?page=1&limit=5
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE



### Dashboard Combined Test
### Search + Filter + Sort + Pagination


GET https://special-rotary-phone-5g49xvj57j49344gq-8000.app.github.dev/api/v1/dashboard/?search=tech&status=Paid&sort=-createdAt&page=1&limit=10
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYWUxYWI0NGU1ZjBkN2ExMDBiNWYzNiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg5Nzk4MzgwLCJleHAiOjE3ODk4MDEzODB9.0f49VLKQMn7EKYE1SmJR_KCqqWDp2JzcBtBiClZoGXE








////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



# BUSINESS TEST
#################################################################

### Create Business 1

POST http://localhost:8000/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc


{
  "businessName": "TechNova Solutions",
  "ownerName": "Rahul Sharma",
  "email": "rahul@technova.com",
  "phone": "9876543210",
  "gstNumber": "27ABCDE1234F1Z5",
  "address": {
    "addressLine1": "FC Road",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "411004"
  },
  "currency": "INR",
  "invoicePrefix": "TN",
  "invoiceStartNumber": 1001
}


### Get Business

GET http://localhost:8000/api/v1/business
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc




# CUSTOMER TEST
#################################################################

### Create Customer 1

POST http://localhost:8000/api/v1/customer
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "customerName": "Amit Patil",
  "email": "amit@gmail.com",
  "phone": "9876543211",
  "companyName": "Apex Technologies",
  "gstNumber": "27AAAAA1111A1Z1",
  "customerType": "Business",
  "notes": "Regular customer",
  "billingAddress": {
    "addressLine1": "Baner Road",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "411045"
  },
  "shippingAddress": {
    "addressLine1": "Baner Road",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "411045"
  }
}



### Create Customer 2

POST http://localhost:8000/api/v1/customer
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "customerName": "Priya Verma",
  "email": "priya@gmail.com",
  "phone": "9876543212",
  "companyName": "CodeWave Pvt Ltd",
  "customerType": "Business",
  "notes": "Premium customer",
  "billingAddress": {
    "addressLine1": "Hinjewadi",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "411057"
  },
  "shippingAddress": {
    "addressLine1": "Hinjewadi",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "411057"
  }
}



### Get Customers

GET http://localhost:8000/api/v1/customer
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc



# PRODUCT TEST
#################################################################

### Create Product 1

POST http://localhost:8000/api/v1/product
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "productName": "Laptop",
  "description": "Dell Inspiron Laptop",
  "category": "Electronics",
  "unit": "piece",
  "price": 55000,
  "taxRate": 18,
  "discount": 5
}



### Create Product 2

POST http://localhost:8000/api/v1/product
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "productName": "Mechanical Keyboard",
  "description": "RGB Gaming Keyboard",
  "category": "Accessories",
  "unit": "piece",
  "price": 3000,
  "taxRate": 18,
  "discount": 10
}



### Create Product 3

POST http://localhost:8000/api/v1/product
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "productName": "Monitor",
  "description": "27 inch 4K Monitor",
  "category": "Electronics",
  "unit": "piece",
  "price": 25000,
  "taxRate": 18,
  "discount": 0
}



### Get Products

GET http://localhost:8000/api/v1/product
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc



# INVOICE TEST
#################################################################

Replace:
- customerId
- productId

with IDs from above responses.


### Create Invoice 1

POST http://localhost:8000/api/v1/invoice
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "customerId": "6a6dbed24fba6cbdd21388f6",
  "items": [
    {
      "productId": "6a6dbef64fba6cbdd21388f8",
      "quantity": 2
    }
  ],
  "dueDate": "2026-08-15",
  "status": "Paid",
  "notes": "First invoice"
}

### Create Invoice 2

POST http://localhost:8000/api/v1/invoice
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "customerId": "6a6dbed24fba6cbdd21388f6",
  "items": [
    {
      "productId": "6a6dbef64fba6cbdd21388f8",
      "quantity": 3
    }
  ],
  "dueDate": "2026-08-20",
  "status": "Pending",
  "notes": "Second invoice"
}




### Create Invoice 3

POST http://localhost:8000/api/v1/invoice
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU1NzY3MzcsImV4cCI6MTc4NTU3OTczN30.RfYeiVwkt1p6peUcoEFiGBb9TfReIqsRvVmisVzdhJc

{
  "customerId": "6a6dbed24fba6cbdd21388f6",
  "items": [
    {
      "productId": "6a6dbef64fba6cbdd21388f8",
      "quantity": 5
    }
  ],
  "dueDate": "2026-09-01",
  "status": "Paid",
  "notes": "Third invoice"
}




##########################################################################################################



Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU3MDMzMTQsImV4cCI6MTc4NTcwNjMxNH0.4hqiMPGoX7-gIUl-Lq7vZhlSzfsyand93u3woL6E7Z0


### Dashboard - Full Data

GET http://localhost:8000/api/v1/dashboard/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU3MDMzMTQsImV4cCI6MTc4NTcwNjMxNH0.4hqiMPGoX7-gIUl-Lq7vZhlSzfsyand93u3woL6E7Z0



### Search Invoice By Customer / Notes

GET http://localhost:8000/api/v1/dashboard/?search=Rahul
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNmQ1MzJhZjU1OWQ4ZmFiYTQyZmQ1ZCIsImVtYWlsIjoiZHNzc0BnbWFpbC5jb20iLCJpYXQiOjE3ODU3MDMzMTQsImV4cCI6MTc4NTcwNjMxNH0.4hqiMPGoX7-gIUl-Lq7vZhlSzfsyand93u3woL6E7Z0
